import { v4 as uuidv4 } from "uuid";

export const INITIAL_PROJECT: Project = {
  id: uuidv4(),
  name: "",
  tasks: [
    {
      id: uuidv4(),
      name: "Flooring",
      materials: [
        {
          id: uuidv4(),
          name: "Hardwood Planks",
          unit: "sq ft",
          quantity: 200,
          unitCost: 16,
          cost: 3200,
        },
        {
          id: uuidv4(),
          name: "Adhesive",
          unit: "gallons",
          quantity: 3,
          unitCost: 50,
          cost: 150,
        },
        {
          id: uuidv4(),
          name: "Underlayment",
          unit: "sq ft",
          quantity: 250,
          unitCost: 1,
          cost: 250,
        },
      ],
      labors: [
        {
          id: uuidv4(),
          role: "Installer",
          unit: "day",
          quantity: 3,
          unitCost: 400,
          cost: 1200,
        },
        { id: uuidv4(), role: "Finisher", unit: "day", quantity: 1, unitCost: 350, cost: 350 },
      ],
      additional: [
        { id: uuidv4(), type: "Permit Fee", cost: 100 },
        { id: uuidv4(), type: "Inspection", cost: 75 },
      ],
      totalCost: 5075,
      profitMargin: 0.0,
      totalPrice: 5075,
    },
    {
      id: uuidv4(),
      name: "Painting",
      materials: [
        {
          id: uuidv4(),
          name: "Interior Paint",
          unit: "gallons",
          quantity: 5,
          unitCost: 50,
          cost: 250,
        },
        {
          id: uuidv4(),
          name: "Paint Rollers & Brushes",
          unit: "set",
          quantity: 1,
          unitCost: 40,
          cost: 40,
        },
        {
          id: uuidv4(),
          name: "Painter's Tape",
          unit: "rolls",
          quantity: 5,
          unitCost: 5,
          cost: 25,
        },
      ],
      labors: [
        {
          id: uuidv4(),
          role: "Painter",
          unit: "day",
          quantity: 1,
          unitCost: 500,
          cost: 500,
        },
        {
          id: uuidv4(),
          role: "Painter",
          unit: "day",
          quantity: 2,
          unitCost: 375,
          cost: 750,
        },
      ],
      additional: [
        {
          id: uuidv4(),
          type: "Permit Fee",
          cost: 60,
        },
      ],
      totalCost: 1625,
      profitMargin: 0.0,
      totalPrice: 1625,
    },
    {
      id: uuidv4(),
      name: "Tile Installation",
      materials: [
        {
          id: uuidv4(),
          name: "Ceramic Tiles",
          unit: "sq ft",
          quantity: 200,
          unitCost: 9,
          cost: 1800,
        },
        {
          id: uuidv4(),
          name: "Tile Adhesive & Grout",
          unit: "bags",
          quantity: 6,
          unitCost: 50,
          cost: 300,
        },
        {
          id: uuidv4(),
          name: "Spacers & Tools",
          unit: "set",
          quantity: 1,
          unitCost: 100,
          cost: 100,
        },
      ],
      labors: [
        {
          id: uuidv4(),
          role: "Tile Cutter",
          unit: "day",
          quantity: 1,
          unitCost: 400,
          cost: 400,
        },
        {
          id: uuidv4(),
          role: "Installer",
          unit: "day",
          quantity: 2,
          unitCost: 500,
          cost: 1000,
        },
      ],
      additional: [],
      totalCost: 3600,
      profitMargin: 0.0,
      totalPrice: 3600,
    },
  ],
  totalCost: 10300,
  profitMargin: 0.0,
  totalPrice: 10300,
  user: {
    id: uuidv4(),
    name: "John Doe",
    phone: "123-456-7890",
    email: "johndoe@example.com",
  },
  customer: {
    id: uuidv4(),
    name: "Jane Smith",
    address: "123 Main St, Springfield",
    phone: "987-654-3210",
    email: "janesmith@example.com",
  },
};
